pipeline:
  - type: kubernetes
    cluster_name: my_cluster
    stdout_output: stdout_router
    stderr_output: stderr_router
  - id: stdout_router
    type: router
    routes:
    - expr: $resource["container.name"] == "nginx-ingress-controller"
      output: nginx.access_parser 
      # TODO how to explicitly tell nginx_parser where it should output? Possibly need:
        # parameters:
        #    output: my_destination
    - expr: "true"
      output: my_destination
  - id: stderr_router
    type: router
    routes:
    - expr: $resource["container.name"] == "nginx-ingress-controller"
      output: nginx.error_parser 
      # TODO how to explicitly tell nginx_parser where it should output? Possibly need:
        # parameters:
        #    output: my_destination
    - expr: "true"
      output: my_destination
  - id: my_destination
    type: example_destination
    foo: bar
